---
title: "HW5 - mm6410"
author: "Mahdi Maktabi"
date: "2024-11-11"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
```

## Question 1

```{r}
bday_sim = function(n) {
  
  bdays = sample(1:365, size = n, replace = TRUE)

  duplicate = length(unique(bdays)) < n

  return(duplicate)
  
}

bday_sim(10)
```

```{r}
sim_res =
  expand_grid(
    n = 2:50,
    iter = 1:10000
  ) |> 
  mutate(res = map_lgl(n, bday_sim)) |> 
  group_by(n) |> 
  summarize(prob = mean(res))

sim_res |> 
  ggplot(aes(x = n, y = prob)) +
  geom_line()
```

The function and figure show the probablity that at least two people in a room share a birthday between (n = 2 and n = 50). We can see that as we increase the number of people in the room, the probability of the same birthday steadily increases. When we get to 50 people, the probability is close to 100%.


## Question 2

```{r, error=TRUE}

sim_mean_pvalue = function(n = 30, mu = 0, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma)
    )
  
  t_test = t.test(sim_data$x, mu = 0)
  
  tibble(
      mu_hat = mean(sim_data$x),
      p_value = broom::tidy(t_test)$p.value)
  
}

sim_mean_pvalue()
```

```{r}
output = vector("list", 5000)

for (i in 1:5000) {
  output[[i]] = sim_mean_pvalue()
}

sim_results = bind_rows(output)

#power = sim_results |> 
  #summarize(power = mean(p_value < 0.05))
```

Now I want to repeat the above code for `symbol("mu") = {1,2,3,4,5,6}`


